version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "docker"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "npm"
      - "dependencies"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
      dnd-kit:
        patterns:
          - "@dnd-kit/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "github-actions"
      - "dependencies"
